<a href="https://colab.research.google.com/github/Balajilp/Advance_House_Price_Prediction/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch learning

## Tensors Basics
A tensors is a generalization of vectors and matrices and is easily understood as multidimentional array.  it has a term and set of 
techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.
In many cases tensors are used as a replacement for Numpy to use the power of GPUs.

These are a data types used in linear Algebra, and like vectors and matrices we can calculate arithmatics operation with tensors

In [1]:
import torch

In [3]:
torch.__version__

'1.10.0+cu111'

In [4]:
import numpy as np

In [5]:
lst = [3, 4, 5, 6]
arr = np.array(lst)
arr

array([3, 4, 5, 6])

In [7]:
arr.dtype

dtype('int64')

## convert numpy to pytorch tensors

In [8]:

tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [9]:
# Indexing similar to numpy
tensors[1:3]

tensor([4, 5])

In [10]:
tensors[1]

tensor(4)

In [12]:
# 'from_numpy' changes in tensors can be done on original numpy array also.  because this method uses same memory location of numpy arrays memory location.
tensors[3] = 100
print(tensors)
print(arr)

tensor([  3,   4,   5, 100])
[  3   4   5 100]


### another method to create tensors..it will give copy of the numpy array

In [13]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [15]:
# here changes not happened in the numpy array
tensor_arr[3] = 10
print(tensor_arr)
print(arr)

tensor([ 3,  4,  5, 10])
[  3   4   5 100]


In [16]:
# Zeros and ones
torch.zeros(2, 3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [17]:
torch.ones(2, 3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [25]:
# indexing in 2d tensors also similar to numpy array
tensor_2d = torch.tensor(np.arange(0, 15).reshape(5, 3))
tensor_2d[:, 1]

tensor([ 1,  4,  7, 10, 13])

## Arithmetic operation on tensors

In [20]:
# arithmetic operation of tensors is pretty much similar to the numpy 
a = torch.tensor([3, 4, 5], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)

In [21]:
a+b

tensor([ 7.,  9., 11.])

In [22]:
torch.add(a, b)

tensor([ 7.,  9., 11.])

In [26]:
c = torch.zeros(3)

In [28]:
# this means whatever expression happen in below we store it in c
torch.add(a, b, out=c)

tensor([ 7.,  9., 11.])

In [29]:
torch.add(a, b).sum()

tensor(27.)

## Dot Product and Multiplication operations

In [30]:
x = torch.tensor([3, 4, 5], dtype=torch.float)
y = torch.tensor([4, 5, 6], dtype=torch.float)

In [31]:
x.mul(y)

tensor([12., 20., 30.])

In [32]:
x.dot(y)

tensor(62.)

In [35]:
# matrix multiplication
m = torch.tensor([[1, 4, 2], [1, 5, 5]], dtype=torch.float)
n = torch.tensor([[5, 7], [8, 6], [9, 11]], dtype=torch.float)

In [37]:
torch.matmul(m, n)

tensor([[55., 53.],
        [90., 92.]])

In [38]:
# instead of using matmul we can use mm. this is the short form of matrix multiplication
torch.mm(m, n)

tensor([[55., 53.],
        [90., 92.]])